### ISSUE TITLE
C support

### ISSUE THREAD

**Issue by azimut** [lostjared/libacidcam#1]
Would it be possible add support for C to these filters? That is for someone to write a program using opencv C api along this filters. End goal for me would be using those C bindings to use it with other language.

**Comment by lostjared** [comment]
Yeah, that would require rewriting a lot of the code. It uses templates, STL, and classes from OpenCV.

**Comment by azimut** [comment]
I was thinking using `extern "C"` https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c

Which seems to be used as `CVAPI` on the includes bundled with opencv. That said my c,c++ knowledge is limited.

**Comment by lostjared** [comment]
Yeah, but it is more than just functions I use references, templates and all kinds of stuff tied to C++.

**Comment by azimut** [comment]
ah gotcha, that resolves my question, thanks!
